# Generated by Django 5.1.1 on 2024-09-18 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "customer_id",
                    models.UUIDField(
                        default=uuid.UUID("4bbd6201-d062-4e64-9e30-1db7204549a0"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("secret_phrase", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("any", "anonymous"), ("knw", "known")], max_length=9
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutritionProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("59cc71a0-1003-4fd2-8e96-7cb1114cbd29"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nutrition_type",
                    models.CharField(
                        choices=[
                            ("Calory", "Calory"),
                            ("Blood Sugar", "Blood Sugar"),
                            ("Protein", "Protein"),
                        ],
                        default="Calory",
                        max_length=20,
                    ),
                ),
                ("check_time", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "token_id",
                    models.UUIDField(
                        default=uuid.UUID("272c87e1-4e07-4172-b158-c14150decebf"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBodyInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("bf06e202-1b21-422f-a52b-805a10449942"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("muscle_mass", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField()),
                ("fat_mass", models.IntegerField(blank=True, null=True)),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customuser",
                    ),
                ),
            ],
        ),
    ]
