# Generated by Django 5.1.1 on 2024-09-20 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="dob",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="customer_id",
            field=models.UUIDField(
                default=uuid.UUID("8c6723b7-cbe5-409b-ada2-42c7ab150f8b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprogress",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("46af8410-43f2-434a-9c4c-28651cdedea6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_id",
            field=models.UUIDField(
                default=uuid.UUID("f524a708-ffb0-4519-9150-f8fa7b95bd91"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userbodyinfo",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e98cc5a7-7f26-449d-a0bc-960b016ba9a8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
